api_version: azuresre.ai/v1
kind: AgentConfiguration
spec:
  name: ApplicationInsightDataGet
  system_prompt: |-
    {Workspaceリソース名}(WorkspaceリソースID}) をターゲットにデータ取得を行います。
    直近1日間のEceptionの情報を収集します
  handoffs:
    - GitHubIssueCheckAndSubmit
  agent_type: Autonomous
  enable_skills: true
  allowed_skills:
    - WorkspaceDataGet
